---
title: "Shiny Workshop ISPA"
author: "Ciampitti Lab"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(ggplot2)
library(shiny)
library(flexdashboard)

# Loading the data
iris_df <- iris
cars_df <- mtcars
```

Template
=====================================

Inputs {.sidebar}
-------------------------------------
### Chart 1 Dropdowns

```{r}
selectInput(
  "scatter_x_var", # Input ID
  label = h5("X axis variable"), 
  choices = names(iris_df)[1:4],
  selected = "Sepal.Width"
)

selectInput(
  "scatter_y_var", 
  label = h5("Y axis variable"), 
  choices = names(iris_df)[1:4],
  selected = "Sepal.Length"
)
```

### Chart 2 Dropdowns

```{r}
selectInput(
  "hist_var", 
  label = h5("X axis variable"), 
  choices = names(iris_df)[1:4],
  selected = "Sepal.Length"
)

sliderInput(
  "hist_bins", 
  label = h5("Number of bins"),
  min = 5,
  max = 50,
  value = 20
)
```

### Chart 3 Dropdowns

```{r}
selectInput(
  "boxplot_y_var", 
  label = h5("Y axis variable"), 
  choices = names(iris_df)[1:4],
  selected = "Sepal.Length"
)
```
    
Column {data-width=600}
-------------------------------------
    
### Chart 1
    
```{r}
output$scatter_plot <- renderPlot({
  ggplot(iris_df, aes_string(x = input$scatter_x_var, y = input$scatter_y_var, color = "Species")) +
    geom_point(size = 3) +
    labs(title = paste("Scatter Plot of", input$scatter_x_var, "x", input$scatter_y_var)) +
    theme_minimal()
})

plotOutput("scatter_plot")
```
   
Column {data-width=400}
-------------------------------------
   
### Chart 2

```{r}
output$hist_out <- renderPlot({
  ggplot(iris_df, aes_string(x = input$hist_var)) +
    geom_histogram(bins = input$hist_bins, fill = "blue", alpha = 0.7) +
    labs(title = paste("Histogram of", input$hist_var, "with", input$hist_bins, "Bins"), x = input$hist_var, y = "Frequency") +
    theme_minimal()
})

plotOutput("hist_out")
```   
 
### Chart 3
    
```{r}
output$boxplot_out <- renderPlot({
  ggplot(iris_df, aes_string(x = "Species", y = input$boxplot_y_var, fill = "Species")) +
    geom_boxplot() +
    labs(title = paste("Box Plot of", input$boxplot_y_var, "by Species"), x = "Species", y = input$boxplot_y_var) +
    theme_minimal()
})

plotOutput("boxplot_out")
```

Now try to built it yourself! {data-orientation=rows}
=====================================

<!-- Create a sidebar -->

<!-- Create a title for the set of controls -->
```{r}
# Create the first input for the X variable

# Create the second input for the Y variable
```

<!-- Create a column for the plot -->

<!-- Create a title for the plot -->
    
```{r}
# Create the output object

# Display the output
```
